version: '3.1'

services:
  user:
    build: ./services/user
    environment:
      NODE_ENV: development
    ports:
      - '50050:50050'
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - '5432:5432'
    restart: always
    environment:
      DEBUG: 'false'
      DB_USER: postgres
      DB_PASS:
      DB_NAME: database_development_10
    volumes:
      -  postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
    notused: