version: '3.1'

services:
  db:
    image: postgres:10
    ports:
      - '5432:5432'
    restart: always
    environment:
      DEBUG: 'false'
      DB_USER: postgres
      DB_PASS:
      DB_NAME: database_development
  api:
    build:
      context: ./
      dockerfile: ./Client/Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - '4000:4000'
    depends_on:
      - db
    volumes:
      - notused:/opt/node_modules
  user:
    build:
      context: ./
      dockerfile: ./Services/user/Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - '50050:50050'
    depends_on:
      - db
    volumes:
      - notused:/opt/node_modules

volumes:
    postgres-data:
    notused: